x=input ("Enter first Number :")
y=input("Enter Second Number :")
sum= (int(x) +int(y))
mul= (int(x)*int(y))
sub= (int(x)-int(y))
div= (int(x)/int(y))
print ("The sum is ", sum)
print ("The mul is ", mul)
print ("The sub is ", sub)
print ("The div is ", div)